### ISSUE TITLE
bug in macro expander - arrays ignored?

### ISSUE THREAD

**Issue by glycerine** [zhemao/glisp#24]
It appears there's some kind of bug in the macro expander. Example below. This might have to do with doing expansions within an array, as in the let-array below.

~~~
> (def h (hash 'a 1 'b 2))
> h
{a 1 b 2}
> (defmac sizer [my-hash]                                                                                                                                                                          
  `(let [n (len ~my-hash)] (println n)))                                                                                                                                                           
> (sizer h)
(sizer h)
error in __main:1: symbol {my-hash 117} not found
> 
~~~

**Comment by glycerine** [comment]
In generator.go
func (gen *Generator) GenerateSyntaxQuote(args []Sexp) 
does not recurse into arrays.

**Comment by zhemao** [comment]
Yeah, you're right. For arrays and hashes, it just puts the literal array in without checking recursively for unquotes. We should recurse for both arrays and hashes. I don't have much spare time these days since I'm busy with Ph.D. research. Do you think you can take care of it? You'll have to add new instruction types to the VM. They should be something like the "squash" instruction I use for syntax quoting lists, except they should generate arrays or hashes instead.

**Comment by glycerine** [comment]
Yeah, I can probably do it, but I really appreciate the confirmation of what's needed. I was thinking that new instruction(s) might be needed, but thought there might be an easier way.  One question is -- does it make sense to spill everything in an array to the stack and then pack it back into the array? Maybe we could get away with expanding and squashing each element in term in isolation....?

**Comment by zhemao** [comment]
I think spilling things out onto the stack and then squashing them all in one go is the right way to go. It isn't very efficient to build up an array in bits and pieces, since that will involve a lot of copying. And since we're only doing this for macro expansions, it's unlikely the array will be very large anyway.

**Comment by zhemao** [comment]
I added you as a collaborator to this repo. You can make your changes in a new branch.

**Comment by glycerine** [comment]
Thanks. I'll give it go.

**Comment by glycerine** [comment]
This is fixed in GoDiesel; commit https://github.com/glycerine/godiesel/commit/33f37342f63655b3688fbe61f286d38b6dd23617  includes the work and some additions.

It will need minor adjustments for Glisp, but that should be straightforward.

**Comment by glycerine** [comment]
As I've renamed my dialect Zygomys, the above mentioned links need to be replaced by these:
https://github.com/glycerine/zygomys/blob/master/repl/generator.go
https://github.com/glycerine/zygomys/blob/master/repl/vm.go
